### ISSUE TITLE
Demo not working (possibly threejs version)

### ISSUE THREAD

**Issue by Utopiah** [upf-gti/IK-threejs#1]
Visiting https://webglstudio.org/demos/IK-threejs/ show nothing and the console reports `Uncaught TypeError: The specifier “three” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”.` for IKSolver.js:1:23

**Comment by evallsg** [comment]
Hi,

Thank you for the warning. We were importing threejs in a way that is not supported by Firefox (other browsers may not support it either). We've already updated it and it should work now.

**Comment by Utopiah** [comment]
Indeed, thanks!
![image](https://user-images.githubusercontent.com/1076655/216011382-33776b5d-cea9-44d9-9668-6306605b0cbb.png)
